
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ian
 */
public class mercadin extends javax.swing.JFrame {

    /**
     * Creates new form mercadin
     */
    public mercadin() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcadcliente = new javax.swing.JFrame();
        cod_cli = new javax.swing.JLabel();
        cod_cli_text = new javax.swing.JLabel();
        nome_cli = new javax.swing.JLabel();
        nome_cli_text = new javax.swing.JTextField();
        rua_cli = new javax.swing.JLabel();
        rua_cli_text = new javax.swing.JTextField();
        num_cli = new javax.swing.JLabel();
        num_cli_text = new javax.swing.JFormattedTextField();
        end_cli = new javax.swing.JLabel();
        end_cli_text = new javax.swing.JTextField();
        tel_cli = new javax.swing.JLabel();
        tel_cli_text = new javax.swing.JFormattedTextField();
        confirm_cli = new javax.swing.JButton();
        cancel_cli = new javax.swing.JButton();
        cli_sexo = new javax.swing.JLabel();
        cli_sexo_text = new javax.swing.JComboBox<>();
        cli_data_cad = new javax.swing.JLabel();
        cli_data_cad_text = new javax.swing.JFormattedTextField();
        cli_status = new javax.swing.JLabel();
        cli_status_text = new javax.swing.JComboBox<>();
        cli_hab = new javax.swing.JLabel();
        cli_hab_text = new javax.swing.JComboBox<>();
        cli_comp = new javax.swing.JLabel();
        cli_comp_text = new javax.swing.JTextField();
        cli_ref = new javax.swing.JLabel();
        cli_ref_text = new javax.swing.JTextField();
        jcadproduto = new javax.swing.JFrame();
        cod_prod = new javax.swing.JLabel();
        cod_prod_text = new javax.swing.JLabel();
        nome_prod = new javax.swing.JLabel();
        nome_prod_text = new javax.swing.JTextField();
        valor_unit = new javax.swing.JLabel();
        valor_kg = new javax.swing.JLabel();
        valor_unit_text = new javax.swing.JFormattedTextField();
        valor_kg_text = new javax.swing.JFormattedTextField();
        reg_prod = new javax.swing.JButton();
        cancel_prod = new javax.swing.JButton();
        tam_prod = new javax.swing.JLabel();
        tam_prod_text = new javax.swing.JComboBox<>();
        tipo_prod = new javax.swing.JLabel();
        tipo_prod_text = new javax.swing.JComboBox<>();
        jcadpedido = new javax.swing.JFrame();
        cod_ped = new javax.swing.JLabel();
        cod_ped_text = new javax.swing.JLabel();
        data_ped = new javax.swing.JLabel();
        data_ped_text = new javax.swing.JFormattedTextField();
        data_entrega_ped = new javax.swing.JLabel();
        data_entrega_ped_text = new javax.swing.JFormattedTextField();
        hora_entrega_ped = new javax.swing.JLabel();
        hora_entrega_ped_text = new javax.swing.JFormattedTextField();
        menu_popup = new javax.swing.JPopupMenu();
        Alterar = new javax.swing.JMenuItem();
        Excluir = new javax.swing.JMenuItem();
        painelmenu = new javax.swing.JPanel();
        cadproduto = new javax.swing.JButton();
        cadcliente = new javax.swing.JButton();
        cadpedido = new javax.swing.JButton();
        histbutton = new javax.swing.JButton();
        statpedido = new javax.swing.JButton();
        cadfuncionario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        painelcentral = new javax.swing.JPanel();
        jprodutos = new javax.swing.JInternalFrame();
        prod_busca_text = new javax.swing.JTextField();
        prod_busca = new javax.swing.JButton();
        prod_add = new javax.swing.JButton();
        prod_info = new javax.swing.JScrollPane();
        prod_table = new javax.swing.JTable();
        jcliente = new javax.swing.JInternalFrame();
        cli_busca_text = new javax.swing.JTextField();
        cli_busca = new javax.swing.JButton();
        cli_add = new javax.swing.JButton();
        cli_info = new javax.swing.JScrollPane();
        cli_table = new javax.swing.JTable();
        jpedido = new javax.swing.JInternalFrame();
        busca_ped_text = new javax.swing.JTextField();
        busca_ped = new javax.swing.JButton();
        add_ped = new javax.swing.JButton();
        info_pad = new javax.swing.JScrollPane();
        table_ped = new javax.swing.JTable();
        jhistorico = new javax.swing.JInternalFrame();
        busca_hist_text = new javax.swing.JTextField();
        busca_hist = new javax.swing.JButton();
        hist_info = new javax.swing.JScrollPane();
        hist_table = new javax.swing.JTable();
        jstatus = new javax.swing.JInternalFrame();
        status_ped_text = new javax.swing.JTextField();
        status_ped = new javax.swing.JButton();
        jfuncionario = new javax.swing.JInternalFrame();

        jcadcliente.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jcadcliente.setTitle("CADASTRO DE CLIENTE");

        cod_cli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cod_cli.setText("Codigo:");

        cod_cli_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cod_cli_text.setText("0000");

        nome_cli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nome_cli.setText("Nome:");

        nome_cli_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rua_cli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rua_cli.setText("Rua:");

        rua_cli_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        num_cli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        num_cli.setText("N :");

        num_cli_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        num_cli_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        end_cli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        end_cli.setText("Bairro:");

        end_cli_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tel_cli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tel_cli.setText("Telefone:");

        try {
            tel_cli_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tel_cli_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tel_cli_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel_cli_textActionPerformed(evt);
            }
        });

        confirm_cli.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        confirm_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registra.png"))); // NOI18N
        confirm_cli.setText("Cadastrar");
        confirm_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_cliActionPerformed(evt);
            }
        });

        cancel_cli.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel_cli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        cancel_cli.setText("Cancelar");

        cli_sexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cli_sexo.setText("Sexo:");

        cli_sexo_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cli_sexo_text.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione--", "Masculino", "Feminino" }));

        cli_data_cad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cli_data_cad.setText("Data de cadastro:");

        cli_data_cad_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        cli_data_cad_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cli_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cli_status.setText("Status do cliente:");

        cli_status_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cli_status_text.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novo", "Usual", "Frequente", "Diario", "VIP" }));

        cli_hab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cli_hab.setText("Habitação:");

        cli_hab_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cli_hab_text.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Condominio", "Apartamento", "Empresa", "Edificio", "Efacil" }));

        cli_comp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cli_comp.setText("Complemento:");

        cli_comp_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cli_ref.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cli_ref.setText("Ponto de referencia:");

        cli_ref_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jcadclienteLayout = new javax.swing.GroupLayout(jcadcliente.getContentPane());
        jcadcliente.getContentPane().setLayout(jcadclienteLayout);
        jcadclienteLayout.setHorizontalGroup(
            jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcadclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcadclienteLayout.createSequentialGroup()
                        .addComponent(end_cli)
                        .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jcadclienteLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cli_ref_text, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jcadclienteLayout.createSequentialGroup()
                                .addGap(699, 699, 699)
                                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jcadclienteLayout.createSequentialGroup()
                                        .addComponent(cli_comp)
                                        .addGap(18, 18, 18)
                                        .addComponent(cli_comp_text, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jcadclienteLayout.createSequentialGroup()
                                        .addComponent(tel_cli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tel_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 232, Short.MAX_VALUE))))
                    .addGroup(jcadclienteLayout.createSequentialGroup()
                        .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jcadclienteLayout.createSequentialGroup()
                                .addComponent(cod_cli)
                                .addGap(41, 41, 41)
                                .addComponent(cod_cli_text))
                            .addGroup(jcadclienteLayout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(confirm_cli)
                                .addGap(264, 264, 264)
                                .addComponent(cancel_cli))
                            .addGroup(jcadclienteLayout.createSequentialGroup()
                                .addComponent(rua_cli)
                                .addGap(18, 18, 18)
                                .addComponent(rua_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jcadclienteLayout.createSequentialGroup()
                                        .addGap(179, 179, 179)
                                        .addComponent(cli_status_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jcadclienteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(num_cli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(num_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(262, 262, 262))
                    .addGroup(jcadclienteLayout.createSequentialGroup()
                        .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jcadclienteLayout.createSequentialGroup()
                                .addComponent(cli_ref)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(end_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jcadclienteLayout.createSequentialGroup()
                                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jcadclienteLayout.createSequentialGroup()
                                        .addComponent(cli_sexo)
                                        .addGap(18, 18, 18)
                                        .addComponent(cli_sexo_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(202, 202, 202)
                                        .addComponent(cli_hab)
                                        .addGap(18, 18, 18)
                                        .addComponent(cli_hab_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jcadclienteLayout.createSequentialGroup()
                                        .addComponent(nome_cli)
                                        .addGap(18, 18, 18)
                                        .addComponent(nome_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jcadclienteLayout.createSequentialGroup()
                                        .addComponent(cli_data_cad)
                                        .addGap(18, 18, 18)
                                        .addComponent(cli_data_cad_text, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cli_status))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jcadclienteLayout.setVerticalGroup(
            jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcadclienteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_cli)
                    .addComponent(cod_cli_text))
                .addGap(29, 29, 29)
                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_cli)
                    .addComponent(nome_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cli_data_cad)
                    .addComponent(cli_data_cad_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cli_sexo)
                    .addComponent(cli_hab_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cli_hab)
                    .addComponent(cli_sexo_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cli_status)
                    .addComponent(cli_status_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rua_cli)
                    .addComponent(rua_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_cli)
                    .addComponent(num_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cli_comp)
                    .addComponent(cli_comp_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(end_cli)
                    .addComponent(cli_ref_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cli_ref)
                    .addComponent(end_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tel_cli)
                    .addComponent(tel_cli_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jcadclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_cli)
                    .addComponent(cancel_cli))
                .addGap(35, 35, 35))
        );

        jcadproduto.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jcadproduto.setTitle("CADASTRO DE PRODUTO");

        cod_prod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cod_prod.setText("Codigo:");

        cod_prod_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cod_prod_text.setText("0000");

        nome_prod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nome_prod.setText("Produto:");

        nome_prod_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        valor_unit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        valor_unit.setText("Valor unitario:");

        valor_kg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        valor_kg.setText("Valor por KG:");

        valor_unit_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        valor_unit_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        valor_kg_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        valor_kg_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        reg_prod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reg_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/confirm.png"))); // NOI18N
        reg_prod.setText("Confirmar");

        cancel_prod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        cancel_prod.setText("Cancelar");

        tam_prod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tam_prod.setText("Tamanho de produto:");

        tam_prod_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tam_prod_text.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Mini" }));

        tipo_prod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tipo_prod.setText("Tipo:");

        tipo_prod_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tipo_prod_text.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "Salgado", "Doce" }));

        javax.swing.GroupLayout jcadprodutoLayout = new javax.swing.GroupLayout(jcadproduto.getContentPane());
        jcadproduto.getContentPane().setLayout(jcadprodutoLayout);
        jcadprodutoLayout.setHorizontalGroup(
            jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcadprodutoLayout.createSequentialGroup()
                .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcadprodutoLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(reg_prod)
                        .addGap(151, 151, 151)
                        .addComponent(cancel_prod))
                    .addGroup(jcadprodutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jcadprodutoLayout.createSequentialGroup()
                                .addComponent(tipo_prod)
                                .addGap(18, 18, 18)
                                .addComponent(tipo_prod_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(tam_prod))
                            .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jcadprodutoLayout.createSequentialGroup()
                                    .addComponent(valor_unit)
                                    .addGap(20, 20, 20)
                                    .addComponent(valor_unit_text, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(valor_kg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valor_kg_text, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jcadprodutoLayout.createSequentialGroup()
                                    .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cod_prod)
                                        .addComponent(nome_prod))
                                    .addGap(86, 86, 86)
                                    .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cod_prod_text)
                                        .addComponent(nome_prod_text, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jcadprodutoLayout.createSequentialGroup()
                        .addGap(617, 617, 617)
                        .addComponent(tam_prod_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jcadprodutoLayout.setVerticalGroup(
            jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcadprodutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_prod)
                    .addComponent(cod_prod_text))
                .addGap(27, 27, 27)
                .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jcadprodutoLayout.createSequentialGroup()
                        .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_prod)
                            .addComponent(nome_prod_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tipo_prod_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tam_prod_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo_prod)))
                    .addComponent(tam_prod))
                .addGap(81, 81, 81)
                .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor_unit)
                    .addComponent(valor_unit_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_kg)
                    .addComponent(valor_kg_text, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(jcadprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_prod)
                    .addComponent(cancel_prod))
                .addGap(33, 33, 33))
        );

        cod_ped.setText("Código:");

        cod_ped_text.setText("0000");

        data_ped.setText("Data do pedido:");

        data_ped_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));

        data_entrega_ped.setText("Data da entrega:");

        data_entrega_ped_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));

        hora_entrega_ped.setText("Hora da Entrega: ");

        hora_entrega_ped_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.MEDIUM))));

        javax.swing.GroupLayout jcadpedidoLayout = new javax.swing.GroupLayout(jcadpedido.getContentPane());
        jcadpedido.getContentPane().setLayout(jcadpedidoLayout);
        jcadpedidoLayout.setHorizontalGroup(
            jcadpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcadpedidoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jcadpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcadpedidoLayout.createSequentialGroup()
                        .addComponent(data_ped)
                        .addGap(18, 18, 18)
                        .addComponent(data_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(data_entrega_ped)
                        .addGap(18, 18, 18)
                        .addComponent(data_entrega_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(hora_entrega_ped)
                        .addGap(18, 18, 18)
                        .addComponent(hora_entrega_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jcadpedidoLayout.createSequentialGroup()
                        .addComponent(cod_ped)
                        .addGap(18, 18, 18)
                        .addComponent(cod_ped_text)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jcadpedidoLayout.setVerticalGroup(
            jcadpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcadpedidoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jcadpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_ped)
                    .addComponent(cod_ped_text))
                .addGap(18, 18, 18)
                .addGroup(jcadpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_ped)
                    .addComponent(data_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_entrega_ped)
                    .addComponent(data_entrega_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_entrega_ped)
                    .addComponent(hora_entrega_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(419, Short.MAX_VALUE))
        );

        Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/config.png"))); // NOI18N
        Alterar.setText("Alterar");
        menu_popup.add(Alterar);

        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/del_prod.png"))); // NOI18N
        Excluir.setText("Excluir");
        menu_popup.add(Excluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELEPÃO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        painelmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bolo.png"))); // NOI18N
        cadproduto.setText("Produtos");
        cadproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadprodutoActionPerformed(evt);
            }
        });

        cadcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cliente_icon.png"))); // NOI18N
        cadcliente.setText("Clientes");
        cadcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadclienteActionPerformed(evt);
            }
        });

        cadpedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/encomenda.png"))); // NOI18N
        cadpedido.setText("Cadastrar pedido");
        cadpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadpedidoActionPerformed(evt);
            }
        });

        histbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_ic_history_48px_352426.png"))); // NOI18N
        histbutton.setText("Historico");
        histbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histbuttonActionPerformed(evt);
            }
        });

        statpedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrega.png"))); // NOI18N
        statpedido.setText("Status do pedido");
        statpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statpedidoActionPerformed(evt);
            }
        });

        cadfuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_User Info_20298.png"))); // NOI18N
        cadfuncionario.setText("Cadastrar funcionario");
        cadfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadfuncionarioActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/map_icon.png"))); // NOI18N
        jButton1.setText("Bairros disponiveis");

        javax.swing.GroupLayout painelmenuLayout = new javax.swing.GroupLayout(painelmenu);
        painelmenu.setLayout(painelmenuLayout);
        painelmenuLayout.setHorizontalGroup(
            painelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelmenuLayout.createSequentialGroup()
                .addComponent(cadproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(histbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadfuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelmenuLayout.setVerticalGroup(
            painelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelmenuLayout.createSequentialGroup()
                .addComponent(cadproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cadfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(statpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(histbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cadpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelcentral.setBackground(new java.awt.Color(235, 235, 235));
        painelcentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jprodutos.setClosable(true);
        jprodutos.setIconifiable(true);
        jprodutos.setMaximizable(true);
        jprodutos.setResizable(true);
        jprodutos.setTitle("PRODUTOS");
        jprodutos.setVisible(false);

        prod_busca_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        prod_busca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prod_busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pesquisa.png"))); // NOI18N
        prod_busca.setText("Buscar");

        prod_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prod_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add_prod.png"))); // NOI18N
        prod_add.setText("Adicionar produto");
        prod_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_addActionPerformed(evt);
            }
        });

        prod_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Tipo", "Tamanho", "Preço unitario", "Preço por Kg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prod_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                prod_tableMouseReleased(evt);
            }
        });
        prod_info.setViewportView(prod_table);

        javax.swing.GroupLayout jprodutosLayout = new javax.swing.GroupLayout(jprodutos.getContentPane());
        jprodutos.getContentPane().setLayout(jprodutosLayout);
        jprodutosLayout.setHorizontalGroup(
            jprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jprodutosLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(prod_busca_text, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prod_busca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jprodutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prod_info)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jprodutosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(prod_add)))
                .addContainerGap())
        );
        jprodutosLayout.setVerticalGroup(
            jprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jprodutosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prod_busca_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod_busca))
                .addGap(31, 31, 31)
                .addComponent(prod_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prod_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcliente.setClosable(true);
        jcliente.setIconifiable(true);
        jcliente.setMaximizable(true);
        jcliente.setResizable(true);
        jcliente.setTitle("CLIENTES");
        jcliente.setVisible(false);

        cli_busca_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cli_busca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cli_busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pesquisa.png"))); // NOI18N
        cli_busca.setText("Buscar");
        cli_busca.setToolTipText("Busque o cliente por parte ou todo o nome");

        cli_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cli_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registra.png"))); // NOI18N
        cli_add.setText("Novo cliente");
        cli_add.setToolTipText("Adicionar novo cliente");
        cli_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cli_addActionPerformed(evt);
            }
        });

        cli_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Sexo", "Data de cadastro", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cli_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cli_tableMouseReleased(evt);
            }
        });
        cli_info.setViewportView(cli_table);

        javax.swing.GroupLayout jclienteLayout = new javax.swing.GroupLayout(jcliente.getContentPane());
        jcliente.getContentPane().setLayout(jclienteLayout);
        jclienteLayout.setHorizontalGroup(
            jclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jclienteLayout.createSequentialGroup()
                .addGroup(jclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jclienteLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(cli_busca_text, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cli_busca)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jclienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cli_info))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jclienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cli_add)))
                .addContainerGap())
        );
        jclienteLayout.setVerticalGroup(
            jclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jclienteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cli_busca)
                    .addComponent(cli_busca_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(cli_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cli_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpedido.setClosable(true);
        jpedido.setMaximizable(true);
        jpedido.setResizable(true);
        jpedido.setTitle("PEDIDOS");
        jpedido.setVisible(false);

        busca_ped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pesquisa.png"))); // NOI18N
        busca_ped.setText("Buscar");

        add_ped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        add_ped.setText("Adicionar pedido");
        add_ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pedActionPerformed(evt);
            }
        });

        table_ped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome do cliente", "Data do pedido", "Status do pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_ped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table_pedMouseReleased(evt);
            }
        });
        info_pad.setViewportView(table_ped);

        javax.swing.GroupLayout jpedidoLayout = new javax.swing.GroupLayout(jpedido.getContentPane());
        jpedido.getContentPane().setLayout(jpedidoLayout);
        jpedidoLayout.setHorizontalGroup(
            jpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpedidoLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(busca_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busca_ped)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info_pad))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_ped)
                .addGap(54, 54, 54))
        );
        jpedidoLayout.setVerticalGroup(
            jpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpedidoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busca_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busca_ped))
                .addGap(42, 42, 42)
                .addComponent(add_ped)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info_pad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jhistorico.setClosable(true);
        jhistorico.setTitle("HISTORICO");
        jhistorico.setVisible(false);

        busca_hist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pesquisa.png"))); // NOI18N
        busca_hist.setText("Buscar");

        hist_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID do pedido", "Nome do cliente", "ID do cliente", "Data do pedido", "Status do cliente", "Status do pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hist_info.setViewportView(hist_table);

        javax.swing.GroupLayout jhistoricoLayout = new javax.swing.GroupLayout(jhistorico.getContentPane());
        jhistorico.getContentPane().setLayout(jhistoricoLayout);
        jhistoricoLayout.setHorizontalGroup(
            jhistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jhistoricoLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(busca_hist_text, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busca_hist)
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(jhistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hist_info)
                .addContainerGap())
        );
        jhistoricoLayout.setVerticalGroup(
            jhistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jhistoricoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jhistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busca_hist_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busca_hist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hist_info, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jstatus.setClosable(true);
        jstatus.setTitle("STATUS DO PEDIDO");
        jstatus.setVisible(false);

        status_ped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pesquisa.png"))); // NOI18N
        status_ped.setText("Buscar");
        status_ped.setToolTipText("");

        javax.swing.GroupLayout jstatusLayout = new javax.swing.GroupLayout(jstatus.getContentPane());
        jstatus.getContentPane().setLayout(jstatusLayout);
        jstatusLayout.setHorizontalGroup(
            jstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstatusLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(status_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(status_ped)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jstatusLayout.setVerticalGroup(
            jstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstatusLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status_ped_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_ped))
                .addContainerGap(431, Short.MAX_VALUE))
        );

        jfuncionario.setClosable(true);
        jfuncionario.setTitle("CADASTRO DE FUNCIONARIO");
        jfuncionario.setVisible(false);

        javax.swing.GroupLayout jfuncionarioLayout = new javax.swing.GroupLayout(jfuncionario.getContentPane());
        jfuncionario.getContentPane().setLayout(jfuncionarioLayout);
        jfuncionarioLayout.setHorizontalGroup(
            jfuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jfuncionarioLayout.setVerticalGroup(
            jfuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelcentralLayout = new javax.swing.GroupLayout(painelcentral);
        painelcentral.setLayout(painelcentralLayout);
        painelcentralLayout.setHorizontalGroup(
            painelcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(painelcentralLayout.createSequentialGroup()
                .addComponent(jprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addGroup(painelcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jhistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(painelcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(painelcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jfuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        painelcentralLayout.setVerticalGroup(
            painelcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcentralLayout.createSequentialGroup()
                .addComponent(jpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(painelcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jhistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(painelcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(painelcentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelcentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadprodutoActionPerformed
        jprodutos.setVisible(true);
        jcliente.setVisible(false);
        jpedido.setVisible(false);
        jhistorico.setVisible(false);
        jstatus.setVisible(false);
        jfuncionario.setVisible(false);
    }//GEN-LAST:event_cadprodutoActionPerformed

    private void cadclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadclienteActionPerformed
        jprodutos.setVisible(false);
        jcliente.setVisible(true);
        jpedido.setVisible(false);
        jhistorico.setVisible(false);
        jstatus.setVisible(false);
        jfuncionario.setVisible(false);
    }//GEN-LAST:event_cadclienteActionPerformed

    private void cadpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadpedidoActionPerformed
        jprodutos.setVisible(false);
        jcliente.setVisible(false);
        jpedido.setVisible(true);
        jhistorico.setVisible(false);
        jstatus.setVisible(false);
        jfuncionario.setVisible(false);
    }//GEN-LAST:event_cadpedidoActionPerformed

    private void histbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histbuttonActionPerformed
        jprodutos.setVisible(false);
        jcliente.setVisible(false);
        jpedido.setVisible(false);
        jhistorico.setVisible(true);
        jstatus.setVisible(false);
        jfuncionario.setVisible(false);
    }//GEN-LAST:event_histbuttonActionPerformed

    private void statpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statpedidoActionPerformed
        jprodutos.setVisible(false);
        jcliente.setVisible(false);
        jpedido.setVisible(false);
        jhistorico.setVisible(false);
        jstatus.setVisible(true);
        jfuncionario.setVisible(false);
    }//GEN-LAST:event_statpedidoActionPerformed

    private void cadfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadfuncionarioActionPerformed
        jprodutos.setVisible(false);
        jcliente.setVisible(false);
        jpedido.setVisible(false);
        jhistorico.setVisible(false);
        jstatus.setVisible(false);
        jfuncionario.setVisible(true);
    }//GEN-LAST:event_cadfuncionarioActionPerformed

    private void tel_cli_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel_cli_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_cli_textActionPerformed

    private void confirm_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_cliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_cliActionPerformed

    private void cli_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cli_addActionPerformed
        jcadcliente.setLocationRelativeTo(null);
        jcadcliente.setBounds(100,100,1100,600);
        jcadcliente.setVisible(true);
    }//GEN-LAST:event_cli_addActionPerformed

    private void prod_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_addActionPerformed
        jcadproduto.setLocationRelativeTo(null);
        jcadproduto.setBounds(100, 100, 1100, 600);
        jcadproduto.setVisible(true);
    }//GEN-LAST:event_prod_addActionPerformed

    private void table_pedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pedMouseReleased
        if(evt.isPopupTrigger()){
            menu_popup.show(this, evt.getXOnScreen(), evt.getYOnScreen());
        }
    }//GEN-LAST:event_table_pedMouseReleased

    private void cli_tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cli_tableMouseReleased
        if(evt.isPopupTrigger()){
            menu_popup.show(this, evt.getXOnScreen(), evt.getYOnScreen());
        }
    }//GEN-LAST:event_cli_tableMouseReleased

    private void prod_tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prod_tableMouseReleased
        if(evt.isPopupTrigger()){
            menu_popup.show(this, evt.getXOnScreen(), evt.getYOnScreen());
        }
    }//GEN-LAST:event_prod_tableMouseReleased

    private void add_pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pedActionPerformed
        jcadpedido.setLocationRelativeTo(null);
        jcadpedido.setBounds(100, 100, 1100, 600);
        jcadpedido.setVisible(true);
    }//GEN-LAST:event_add_pedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mercadin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mercadin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mercadin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mercadin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mercadin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Alterar;
    private javax.swing.JMenuItem Excluir;
    private javax.swing.JButton add_ped;
    private javax.swing.JButton busca_hist;
    private javax.swing.JTextField busca_hist_text;
    private javax.swing.JButton busca_ped;
    private javax.swing.JTextField busca_ped_text;
    private javax.swing.JButton cadcliente;
    private javax.swing.JButton cadfuncionario;
    private javax.swing.JButton cadpedido;
    private javax.swing.JButton cadproduto;
    private javax.swing.JButton cancel_cli;
    private javax.swing.JButton cancel_prod;
    private javax.swing.JButton cli_add;
    private javax.swing.JButton cli_busca;
    private javax.swing.JTextField cli_busca_text;
    private javax.swing.JLabel cli_comp;
    private javax.swing.JTextField cli_comp_text;
    private javax.swing.JLabel cli_data_cad;
    private javax.swing.JFormattedTextField cli_data_cad_text;
    private javax.swing.JLabel cli_hab;
    private javax.swing.JComboBox<String> cli_hab_text;
    private javax.swing.JScrollPane cli_info;
    private javax.swing.JLabel cli_ref;
    private javax.swing.JTextField cli_ref_text;
    private javax.swing.JLabel cli_sexo;
    private javax.swing.JComboBox<String> cli_sexo_text;
    private javax.swing.JLabel cli_status;
    private javax.swing.JComboBox<String> cli_status_text;
    private javax.swing.JTable cli_table;
    private javax.swing.JLabel cod_cli;
    private javax.swing.JLabel cod_cli_text;
    private javax.swing.JLabel cod_ped;
    private javax.swing.JLabel cod_ped_text;
    private javax.swing.JLabel cod_prod;
    private javax.swing.JLabel cod_prod_text;
    private javax.swing.JButton confirm_cli;
    private javax.swing.JLabel data_entrega_ped;
    private javax.swing.JFormattedTextField data_entrega_ped_text;
    private javax.swing.JLabel data_ped;
    private javax.swing.JFormattedTextField data_ped_text;
    private javax.swing.JLabel end_cli;
    private javax.swing.JTextField end_cli_text;
    private javax.swing.JScrollPane hist_info;
    private javax.swing.JTable hist_table;
    private javax.swing.JButton histbutton;
    private javax.swing.JLabel hora_entrega_ped;
    private javax.swing.JFormattedTextField hora_entrega_ped_text;
    private javax.swing.JScrollPane info_pad;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jcadcliente;
    private javax.swing.JFrame jcadpedido;
    private javax.swing.JFrame jcadproduto;
    private javax.swing.JInternalFrame jcliente;
    private javax.swing.JInternalFrame jfuncionario;
    private javax.swing.JInternalFrame jhistorico;
    private javax.swing.JInternalFrame jpedido;
    private javax.swing.JInternalFrame jprodutos;
    private javax.swing.JInternalFrame jstatus;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JLabel nome_cli;
    private javax.swing.JTextField nome_cli_text;
    private javax.swing.JLabel nome_prod;
    private javax.swing.JTextField nome_prod_text;
    private javax.swing.JLabel num_cli;
    private javax.swing.JFormattedTextField num_cli_text;
    private javax.swing.JPanel painelcentral;
    private javax.swing.JPanel painelmenu;
    private javax.swing.JButton prod_add;
    private javax.swing.JButton prod_busca;
    private javax.swing.JTextField prod_busca_text;
    private javax.swing.JScrollPane prod_info;
    private javax.swing.JTable prod_table;
    private javax.swing.JButton reg_prod;
    private javax.swing.JLabel rua_cli;
    private javax.swing.JTextField rua_cli_text;
    private javax.swing.JButton statpedido;
    private javax.swing.JButton status_ped;
    private javax.swing.JTextField status_ped_text;
    private javax.swing.JTable table_ped;
    private javax.swing.JLabel tam_prod;
    private javax.swing.JComboBox<String> tam_prod_text;
    private javax.swing.JLabel tel_cli;
    private javax.swing.JFormattedTextField tel_cli_text;
    private javax.swing.JLabel tipo_prod;
    private javax.swing.JComboBox<String> tipo_prod_text;
    private javax.swing.JLabel valor_kg;
    private javax.swing.JFormattedTextField valor_kg_text;
    private javax.swing.JLabel valor_unit;
    private javax.swing.JFormattedTextField valor_unit_text;
    // End of variables declaration//GEN-END:variables
}
